(in-package #:cl-gcrypt)

(export '#.(lispify "gcry_cipher_hd_t" 'type))

(export '#.(lispify "GCRY_CIPHER_NONE" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_IDEA" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_3DES" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_CAST5" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_BLOWFISH" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_SAFER_SK128" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_DES_SK" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_AES" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_AES192" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_AES256" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_TWOFISH" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_ARCFOUR" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_DES" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_TWOFISH128" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_SERPENT128" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_SERPENT192" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_SERPENT256" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_RFC2268_40" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_RFC2268_128" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_SEED" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_CAMELLIA128" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_CAMELLIA192" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_CAMELLIA256" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_SALSA20" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_SALSA20R12" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_GOST28147" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_CHACHA20" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_GOST28147_MESH" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_SM4" 'enumvalue))

(export '#.(lispify "GCRY_CIPHER_MODE_NONE" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_MODE_ECB" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_MODE_CFB" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_MODE_CBC" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_MODE_STREAM" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_MODE_OFB" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_MODE_CTR" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_MODE_AESWRAP" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_MODE_CCM" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_MODE_GCM" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_MODE_POLY1305" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_MODE_OCB" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_MODE_CFB8" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_MODE_XTS" 'enumvalue))
(export '#.(lispify "GCRY_CIPHER_MODE_EAX" 'enumvalue))

(export '#.(namify-function "gcry_cipher_open"))
(export '#.(namify-function "gcry_cipher_setkey"))
(export '#.(namify-function "gcry_cipher_encrypt"))
(export '#.(namify-function "gcry_cipher_close"))
(export '#.(namify-function "gcry_cipher_decrypt"))
(export '#.(namify-function "gcry_cipher_get_algo_keylen"))
(export '#.(namify-function "gcry_cipher_get_algo_blklen"))
(export '#.(namify-function "gcry_cipher_algo_name"))
(export '#.(namify-function "gcry_cipher_map_name"))
(export '#.(namify-function "gcry_cipher_mode_from_oid"))
(export '#.(namify-function "gcry_cipher_info"))
(export '#.(namify-function "gcry_cipher_algo_info"))
(export '#.(namify-function "gcry_cipher_test_algo"))
(export '#.(namify-function "gcry_cipher_ctl"))
(export '#.(namify-function "gcry_cipher_reset"))
(export '#.(namify-function "gcry_cipher_setiv"))
(export '#.(namify-function "gcry_cipher_gettag"))
(export '#.(namify-function "gcry_cipher_authenticate"))
(export '#.(namify-function "gcry_cipher_checktag"))
(export '#.(namify-function "gcry_cipher_final"))
(export '#.(namify-function "gcry_cipher_setctr"))
(export '#.(namify-function "gcry_cipher_sync"))
(export '#.(namify-function "gcry_cipher_cts"))
(export '#.(namify-function "gcry_cipher_set_sbox"))
