(in-package :cl-gcrypt)

(export '#.(lispify "gcry_md_hd_t" 'type))
(export '#.(lispify "gcry_md_handle" 'type))
(export '#.(lispify "gcry_error_t" 'type))
(export '#.(lispify "gcry_buffer_t" 'type))
(export 'size)
(export 'off)
(export 'len)
(export 'buf)

;; algos
(export '#.(lispify "GCRY_MD_NONE" 'enumvalue))
(export '#.(lispify "GCRY_MD_MD5" 'enumvalue))
(export '#.(lispify "GCRY_MD_SHA1" 'enumvalue))
(export '#.(lispify "GCRY_MD_RMD160" 'enumvalue))
(export '#.(lispify "GCRY_MD_MD2" 'enumvalue))
(export '#.(lispify "GCRY_MD_TIGER" 'enumvalue))
(export '#.(lispify "GCRY_MD_HAVAL" 'enumvalue))
(export '#.(lispify "GCRY_MD_SHA256" 'enumvalue))
(export '#.(lispify "GCRY_MD_SHA384" 'enumvalue))
(export '#.(lispify "GCRY_MD_SHA512" 'enumvalue))
(export '#.(lispify "GCRY_MD_SHA224" 'enumvalue))
(export '#.(lispify "GCRY_MD_MD4" 'enumvalue))
(export '#.(lispify "GCRY_MD_CRC32" 'enumvalue))
(export '#.(lispify "GCRY_MD_CRC32_RFC1510" 'enumvalue))
(export '#.(lispify "GCRY_MD_CRC24_RFC2440" 'enumvalue))
(export '#.(lispify "GCRY_MD_WHIRLPOOL" 'enumvalue))
(export '#.(lispify "GCRY_MD_TIGER1" 'enumvalue))
(export '#.(lispify "GCRY_MD_TIGER2" 'enumvalue))
(export '#.(lispify "GCRY_MD_GOSTR3411_94" 'enumvalue))
(export '#.(lispify "GCRY_MD_STRIBOG256" 'enumvalue))
(export '#.(lispify "GCRY_MD_STRIBOG512" 'enumvalue))
(export '#.(lispify "GCRY_MD_GOSTR3411_CP" 'enumvalue))
(export '#.(lispify "GCRY_MD_SHA3_224" 'enumvalue))
(export '#.(lispify "GCRY_MD_SHA3_256" 'enumvalue))
(export '#.(lispify "GCRY_MD_SHA3_384" 'enumvalue))
(export '#.(lispify "GCRY_MD_SHA3_512" 'enumvalue))
(export '#.(lispify "GCRY_MD_SHAKE128" 'enumvalue))
(export '#.(lispify "GCRY_MD_SHAKE256" 'enumvalue))
(export '#.(lispify "GCRY_MD_BLAKE2B_512" 'enumvalue))
(export '#.(lispify "GCRY_MD_BLAKE2B_384" 'enumvalue))
(export '#.(lispify "GCRY_MD_BLAKE2B_256" 'enumvalue))
(export '#.(lispify "GCRY_MD_BLAKE2B_160" 'enumvalue))
(export '#.(lispify "GCRY_MD_BLAKE2S_256" 'enumvalue))
(export '#.(lispify "GCRY_MD_BLAKE2S_224" 'enumvalue))
(export '#.(lispify "GCRY_MD_BLAKE2S_160" 'enumvalue))
(export '#.(lispify "GCRY_MD_BLAKE2S_128" 'enumvalue))

;; flags
(export '#.(lispify "GCRY_MD_FLAG_SECURE" 'enumvalue))
(export '#.(lispify "GCRY_MD_FLAG_HMAC" 'enumvalue))
(export '#.(lispify "GCRY_MD_FLAG_BUGEMU1" 'enumvalue))

;; functions
(export '#.(namify-function "gcry_md_open"))
(export '#.(namify-function "gcry_md_close"))
(export '#.(namify-function "gcry_md_enable"))
(export '#.(namify-function "gcry_md_copy"))
(export '#.(namify-function "gcry_md_reset"))
(export '#.(namify-function "gcry_md_write"))
(export '#.(namify-function "gcry_md_read"))
(export '#.(namify-function "gcry_md_hash_buffer"))
(export '#.(namify-function "gcry_md_get_algo"))
(export '#.(namify-function "gcry_md_get_algo_dlen"))
(export '#.(namify-function "gcry_md_is_enabled"))
(export '#.(namify-function "gcry_md_is_secure"))
(export '#.(namify-function "gcry_md_algo_name"))
(export '#.(namify-function "gcry_md_map_name"))
(export '#.(namify-function "gcry_md_setkey"))
(export '#.(namify-function "gcry_md_algo_info"))
(export '#.(namify-function "gcry_md_test_algo"))
(export '#.(namify-function "gcry_md_get_asnoid"))
(export '#.(namify-function "gcry_md_ctl"))
(export '#.(namify-function "gcry_md_final"))
(export '#.(namify-function "gcry_md_putc"))
(export '#.(namify-function "gcry_md_debug"))
(export '#.(namify-function "gcry_md_info"))
(export '#.(namify-function "gcry_md_extract"))
(export '#.(namify-function "gcry_md_hash_buffers"))
